name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.2.0
        with:
          jekyll_src: "./"
          target_branch: "gh-pages"
          token: ${{ secrets.GITHUB_TOKEN }}
